spring:
  datasource:
    url: jdbc:mariadb://bit911215.cebga7nnwvvl.ap-northeast-2.rds.amazonaws.com:3306/bit911215
    username: bit911215
    password: Wjdgus2580
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: jwtSecret

