spring:
  datasource:
    url: jdbc:mariadb://bit911215.cebga7nnwvvl.ap-northeast-2.rds.amazonaws.com:3306/bit911215
    username: bit911215
    password: Wjdgus2580
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
  jwt:
    secret: jwtSecret


UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token